spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

sqs:
  queue:
    url: ${SQS_QUEUE_URL}

attachments:
  bucket:
    name: ${ATTACHMENTS_BUCKET_NAME}
