spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/supportdesk
    username: supportdesk_admin
    password: localpassword
  jpa:
    show-sql: true

sqs:
  queue:
    url: http://localhost:9324/queue/supportdesk-ticket-routing #to prevent errors when running locally without SQS.

attachments:
  bucket:
    name: local-attachments-bucket # not used locally
